name: CI Isolation CI Build

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'maven'
      - name: Write ADLSG2 accountkey file
        run: |
          echo "$ACCOUNTKEY" > accountkey.txt
        env:
          ACCOUNTKEY: ${{ secrets.ACCOUNTKEY }}
      - name: Write ADLSG2 accountname file
        run: |
          echo "$ACCOUNTNAME" > accountname.txt
        env:
          ACCOUNTNAME: ${{ secrets.ACCOUNTNAME }}
      - name: Run tests and build with Maven
        run: mvn --batch-mode --update-snapshots clean verify --file ci-isolation/pom.xml -DtrimStackTrace=false