name: Release Droid - Prepare Original Checksum

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Write ADLSG2 accountkey file
        run: |
          echo "$ACCOUNTKEY" > accountkey.txt
        env:
          ACCOUNTKEY: ${{ secrets.ACCOUNTKEY }}
      - name: Write ADLSG2 accountname file
        run: |
          echo "$ACCOUNTNAME" > accountname.txt
        env:
          ACCOUNTNAME: ${{ secrets.ACCOUNTNAME }}
      - name: Run tests and build with Maven
        run: mvn --batch-mode clean verify --file pom.xml
      - name: Prepare checksum
        run: find target -maxdepth 1 -name *.jar -exec sha256sum "{}" + > original_checksum
      - name: Upload checksum to the artifactory
        uses: actions/upload-artifact@v2
        with:
          name: original_checksum
          retention-days: 5
          path: original_checksum